- hosts: 127.0.0.1
  connection: local
  #become: true

  tasks:

    - name: Update all packages to the latest version
      apt:
        name: aptitude 
        upgrade: yes

    - name: Download Filebeat
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-amd64.deb
        dest: /home/ubuntu/filebeat-7.1.1-amd64.deb
        mode: 0440
    
    - name: Install Filebeat
      apt:
        deb: /home/ubuntu/filebeat-7.1.1-amd64.deb

    - name: Enable Filebeat System
      command: filebeat modules enable system
    
    - name: Download Metricbeat
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.1.1-amd64.deb
        dest: /home/ubuntu/metricbeat-7.1.1-amd64.deb
        mode: 0440
      
    - name: Install Metricbeat
      apt:
        deb: /home/ubuntu/metricbeat-7.1.1-amd64.deb
